jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build
      uses: gradle/gradle-build-action@3bfe3a46584a206fb8361cdedd0647b0c4204232
      with:
        arguments: build
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___build.yml
